name: reddit_style_comments
description: "A highly customizable Flutter package for building recursive, Reddit-style threaded comment trees with support for voting logic, nested replies, and smooth animations."
version: 0.0.1
homepage: https://github.com/Ashar-Azeem/Reddit-Style-Comments
repository: https://github.com/Ashar-Azeem/Reddit-Style-Comments
issue_tracker: https://github.com/Ashar-Azeem/Reddit-Style-Comments/issues

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  equatable: ^2.0.8
  expandable_text: ^2.3.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # If you decided to keep the avatars in the package, 
  # don't forget to uncomment and list them here:
  # assets:
  #   - assets/Avatars/